<a href="https://colab.research.google.com/github/A-THAKUR22/AVISOFTAT/blob/main/Assignment14_14_2_24.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Program to test whether each element of a 1-D array is also present in a second array.

In [40]:

import numpy as np
a=np.array([10,20,30,40,60])
b=np.array([0,40])

result=np.isin(a,b)
print(result)

[False False False  True False]


NumPy program to get the unique elements of an array

In [43]:
c=np.array([10,10,20,30,40,30])
d1=[]
r=int(input("Enter the number of rows:"))
col=int(input("Enter the number of columns:"))
for i in range(r):
  row=[]
  for j in range(col):
    element=int(input(f"Enter the elements at ({i+1},{j+1}) :"))
    row.append(element)
  d1.append(row)
d=np.array(d1)
result=np.unique(c)
sec_result=np.unique(d)
print(result,sec_result)

Enter the number of rows:2
Enter the number of columns:2
Enter the elements at (1,1) :1
Enter the elements at (1,2) :1
Enter the elements at (2,1) :2
Enter the elements at (2,2) :3
[10 20 30 40] [1 2 3]


NumPy program to sort an along the first, last axis of an array.

In [51]:
c1=[]
r=int(input("Enter the number of rows:"))
col=int(input("Enter the number of columns:"))
for i in range(r):
  row=[]
  for j in range(col):
    element=int(input(f"Enter the elements at ({i+1},{j+1}) :"))
    row.append(element)
  c1.append(row)
c=np.array(c1)

result=np.sort(c, axis=1)
result2=np.sort(c, axis=0)
new=np.sort(result2)
print(f" Sort along last axis:\n{new}")
print(f"Sort along first axis:\n{result2}")

Enter the number of rows:2
Enter the number of columns:2
Enter the elements at (1,1) :4
Enter the elements at (1,2) :6
Enter the elements at (2,1) :2
Enter the elements at (2,2) :1
 Sort along last axis:
[[1 2]
 [4 6]]
Sort along first axis:
[[2 1]
 [4 6]]


NumPy program to count the occurrence of a specified item in a given NumPy array.

In [47]:
import pandas as pd
a=[]
length=int(input("Enter the size on ndarray:"))
for i in range(length):
  element=int(input(f"Enter the element {i+1}: "))
  a.append(element)
a1=np.array(a)
result=pd.value_counts(a1)
print(list(result))

Enter the size on ndarray:15
Enter the element 1: 10
Enter the element 2: 20
Enter the element 3: 20
Enter the element 4: 20
Enter the element 5: 20
Enter the element 6: 0
Enter the element 7: 20
Enter the element 8: 30
Enter the element 9: 30
Enter the element 10: 30
Enter the element 11: 0
Enter the element 12: 0
Enter the element 13: 20
Enter the element 14: 20
Enter the element 15: 0
[7, 4, 3, 1]


NumPy program to remove nan values from a given array.

In [56]:
input1=input("Enter the values in array separated by spaces :")
elements=input1.split()
a1=np.array([int(x) if x != 'nan' else np.nan for x in elements])
result=a1[~np.isnan(a1)]
print(result)

Enter the values in array separated by spaces :200 300 nan nan 700
[200. 300. 700.]


NumPy program to calculate percentiles for a sequence or single-dimensional NumPy array.

In [64]:
a=[]
length=int(input("Enter the size on ndarray:"))
for i in range(length):
  element=int(input(f"Enter the element {i+1}: "))
  a.append(element)
a1=np.array(a)
median=np.percentile(a1,50)
med2=np.percentile(a1,40)
med3=np.percentile(a1,90)
print(f"50th percentile : {median}")
print(f"40th percentile : {med2}")
print(f"90th percentile : {med3}")

Enter the size on ndarray:5
Enter the element 1: 1
Enter the element 2: 2
Enter the element 3: 3
Enter the element 4: 4
Enter the element 5: 5
50th percentile : 3.0
40th percentile : 2.6
90th percentile : 4.6


NumPy program to find indices of elements equal to zero in a NumPy array.

In [66]:
a=[]
length=int(input("Enter the size on ndarray:"))
for i in range(length):
  element=int(input(f"Enter the element {i+1}: "))
  a.append(element)
a1=np.array(a)
#new=[i for i in range(length) if a1[i]==0 ]
new=np.where(a1==0)[0]
print(new)

Enter the size on ndarray:11
Enter the element 1: 1
Enter the element 2: 0
Enter the element 3: 2
Enter the element 4: 0
Enter the element 5: 3
Enter the element 6: 0
Enter the element 7: 4
Enter the element 8: 5
Enter the element 9: 6
Enter the element 10: 7
Enter the element 11: 8
[1 3 5]


NumPy program to round elements of the array to the nearest integer, and then calculate the abslute value element wise.

In [70]:
a=[]
length=int(input("Enter the size on ndarray:"))
for i in range(length):
  element=float(input(f"Enter the element {i+1}: "))
  a.append(element)
a1=np.array(a)
a2=np.absolute(a1)
result=np.round(a2)
print(result)


Enter the size on ndarray:7
Enter the element 1: -0.7
Enter the element 2: -1.5
Enter the element 3: -1.7
Enter the element 4: 0.3
Enter the element 5: 1.5
Enter the element 6: 1.8
Enter the element 7: 2.0
[1. 2. 2. 0. 2. 2. 2.]


NumPy program to calculate the difference between neighboring elements, element-wise, and prepend [0, 0] and append[200] to a given array.

In [78]:
a=[]
length=int(input("Enter the size on ndarray:"))
for i in range(length):
  element=float(input(f"Enter the element {i+1}: "))
  a.append(element)
a1=np.array(a)
diff=np.zeros_like(a1)
for i in range(1,length):
  diff[i]=a1[i]-a1[i-1]
diff=np.append(diff,200)
diff=np.insert(diff,0,[0])
print(diff)


Enter the size on ndarray:5
Enter the element 1: 1
Enter the element 2: 3
Enter the element 3: 5
Enter the element 4: 7
Enter the element 5: 0
[  0.   0.   2.   2.   2.  -7. 200.]


NumPy program to get the indices of the sorted elements of a given array.

In [79]:
a=np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])
result=np.argsort(a)
print(result)

[0 3 4 6 1 5 2]


NumPy program to partition a given array in a specified position and move all the smaller elements values to the left of the partition, and the remaining values to the right, in arbitrary order (based on random choice).

In [85]:
a=[]
length=int(input("Enter the size on ndarray:"))
for i in range(length):
  element=float(input(f"Enter the element {i+1}: "))
  a.append(element)
a1=np.array(a)
new=np.partition(a1,length//2)
print(new)

Enter the size on ndarray:8
Enter the element 1: 70
Enter the element 2: 50
Enter the element 3: 20
Enter the element 4: 30
Enter the element 5: -11
Enter the element 6: 60
Enter the element 7: 50
Enter the element 8: 40
[-11.  30.  20.  40.  50.  50.  60.  70.]


Compute the euclidean distance between two arrays a and b.

In [94]:
a=[]
length=int(input("Enter the size on ndarray:"))
for i in range(length):
  element=float(input(f"Enter the element {i+1}: "))
  a.append(element)
a1=np.array(a)
a_s=[]
length=int(input("Enter the size of second ndarray:"))
for i in range(length):
  element=float(input(f"Enter the element {i+1}: "))
  a_s.append(element)
a2=np.array(a_s)
diff=a1-a2
squared=diff**2
sum_sq=np.sum(squared)
euclid=np.sqrt(sum_sq)
print(euclid)

Enter the size on ndarray:5
Enter the element 1: 1
Enter the element 2: 2
Enter the element 3: 3
Enter the element 4: 4
Enter the element 5: 5
Enter the size of second ndarray:5
Enter the element 1: 4
Enter the element 2: 5
Enter the element 3: 6
Enter the element 4: 7
Enter the element 5: 8
6.708203932499369


Find all the peaks in a 1D numpy array a. Peaks are points surrounded by smaller values on both sides.

In [92]:
a=[]
length=int(input("Enter the size on ndarray:"))
for i in range(length):
  element=float(input(f"Enter the element {i+1}: "))
  a.append(element)
a1=np.array(a)
peaks=[]
for i in range(length-1):
  if a1[i]>a1[i-1] and a1[i]>a1[i+1]:
    peaks.append(i)
result=np.array([peaks])
print(result)

Enter the size on ndarray:8
Enter the element 1: 1
Enter the element 2: 3
Enter the element 3: 7
Enter the element 4: 1
Enter the element 5: 2
Enter the element 6: 6
Enter the element 7: 0
Enter the element 8: 1
[[2 5]]


Find the index of nth repetition of number i .

In [101]:
a=[]
length=int(input("Enter the size on ndarray:"))
for i in range(length):
  element=float(input(f"Enter the element {i+1}: "))
  a.append(element)
a1=np.array(a)
n=int(input("Enter the nth repetition of a number:"))
i=int(input("Enter the number you want to find:"))
result=np.where(a1==i)[0]
if n<= len(result):
  print(result[n-1])


Enter the size on ndarray:13
Enter the element 1: 1
Enter the element 2: 2
Enter the element 3: 1
Enter the element 4: 1
Enter the element 5: 3
Enter the element 6: 4
Enter the element 7: 3
Enter the element 8: 1
Enter the element 9: 1
Enter the element 10: 2
Enter the element 11: 1
Enter the element 12: 1
Enter the element 13: 2
Enter the nth repetition of a number:5
Enter the number you want to find:1
8
